name: Sync GitHub Issues

on:
  issues:
    types:
      - opened
      - closed
      - labeled
      - unlabeled
  workflow_dispatch:

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install -U pip
          pip install -r scripts/requirements.txt
      - working-directory: scripts
        run: python get-repo-issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "microtask-table.csv project-table.csv"
          message: "Update tables of issues"
          new_branch: "issue-data"
