name: Accessibility task
description: |
  Propose an accessibility improvement,
  following WAVE report in https://github.com/jupyterhub/outreachy/issues/38.

title: "Accessibility: "
labels:
  - outreachy-dec22
  - "project: improve-accessibility"
  - "needs:review"
body:
  - type: markdown
    attributes:
      value: >
        Thank you for improving accessibility of a Jupyter page!

        If you're here, you have produced a WAVE accessibility report (as described in https://github.com/jupyterhub/outreachy/issues/38).
        Now it's time to propose a _specific_ improvement to the HTML document,
        which should address one or more accessibility issues.
        please propose an _improvement_ to the HTML document
        that will solve one or more issues found by WAVE.

        Below, please provide:

        - the URL of the page you are working on
        - the relevant accessibility report from WAVE
          (or a link to your comment in #38)
        - the HTML (or CSS) you propose to change
        - the HTML (or CSS) you propose to change it _to_
        - Any details/discussion if you have more systematic/structural changes
          to suggest that aren't easily represented as changes in HTML.
          Please be as specific as you can.

  - type: input
    id: page
    attributes:
      label: What page is this for?
      placeholder: |
        https://...
    validations:
      required: true

  - type: textarea
    id: report
    attributes:
      label: WAVE accessibility report
      description: >
        Provide the WAVE accessibility report,
        or the relevant section of it,
        including a screenshot.
    validations:
      required: true

  - type: textarea
    id: html-before
    attributes:
      label: The HTML element to be changed
      description: >
        Provide the HTML/CSS of the element(s) to change,
        as they are on the page.
      render: html
    validations:
      required: true

  - type: textarea
    id: html-after
    attributes:
      label: Your proposed HTML (or CSS), after change
      description: >
        Provide your proposal that the HTML/CSS _should_ be,
        in order to resolve the issue(s).
      render: html

  - type: textarea
    id: more
    attributes:
      label: More info
      description: >
        Anything more you want to share?
        Suggestions that don't fit in HTML/CSS changes?
        Add it here.
