name: 🧩 Pytest plugin task
description: |
  Share the work that you've done as part of https://github.com/jupyterhub/outreachy/issues/40

title: "My pytest plugin"
labels:
  - "outreachy-dec22"
  - "project: hub-pytest-plugin"
  - "needs:review"
body:
  - type: markdown
    attributes:
      value: >

        Thank you for your interest in improving the JupyterHub testing infrastructure!

        If you're here, you have worked on creating a pytest plugin that you integrated
        in your own fork of `FirstUseAuthenticator`, as described in issue
        https://github.com/jupyterhub/outreachy/issues/40.

        Below, please provide:

        - The URL of the pytest plugin you have created

        - The URL to your fork of https://github.com/jupyterhub/firstuseauthenticator, where you have integrated the plugin

        - Whether or not you managed to run the `FirstUseAuthenticator` tests succesfully

        - If the tests don't run, please describe the issue you're having and where you need help

  - type: input
    id: plugin
    attributes:
      label: Please share the URL of pytest plugin you have created?
      placeholder: |
        https://github.com/...
    validations:
      required: true

  - type: input
    id: fork
    attributes:
      label: Please share the URL to your fork of `FirstUseAuthenticator` where you have integrated the plugin
      placeholder: |
        https://github.com/...
    validations:
      required: true

  - type: dropdown
    id: tests-work
    attributes:
      label: Whether or not you managed to run the `FirstUseAuthenticator` tests succesfully
      description: |
        Please click the `Yes` box if the `FirstUseAuthenticator` tests complete succesfully in your fork of `FirstUseAuthenticator`
        and the `No` box if they fail, or you are stuck and need help.
      options:
        - Yes, the tests run
        - No, the tests don't run
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Issue description
      description: >
        If you chose the `No` option above, please describe the best as you can the issue,
        sharing any errors you're seeing to help us understand the issue.
    validations:
      required: false
